name: publish
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - uses: ./.github/actions/build-core
      - uses: ./.github/actions/build-svelte
      - uses: ./.github/actions/build-vue
      - run: pnpm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_PUBLISH_TOKEN }}
      - run: pnpm publish --access public --no-git-checks
